"""
SecureBank — SQLAlchemy ORM models.

I define the four core database tables here:

* ``StaffUser``   — internal staff accounts with role-based
  access control and account-lockout tracking.
* ``Customer``    — customer records with balance, status,
  and relationships to their transactions.
* ``Transaction`` — deposit, withdrawal, and transfer records
  linked to one or two customer accounts.
* ``AuditLog``    — immutable record of every significant
  event in the system.

All ``created_at`` and ``updated_at`` columns use UTC
timestamps via the module-level ``_now()`` helper.
"""

from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
)
from sqlalchemy.orm import relationship

from app.database import Base


def _now():
    """Return the current UTC datetime as a timezone-aware value.

    I use this helper instead of ``datetime.utcnow`` because
    ``utcnow`` is deprecated in Python 3.12+ and returns a
    naive datetime that has no timezone information attached.
    """
    return datetime.now(timezone.utc)


class StaffUser(Base):
    """Represents a member of staff who can log into the system.

    Roles (lowest to highest privilege):
        staff       — view customers and process transactions.
        manager     — full access: customer management, staff
                      management, audit logs, CSV export.
        superadmin  — all manager permissions plus the ability
                      to unlock other manager/superadmin accounts.

    Account lockout:  after ``MAX_FAILED_LOGIN_ATTEMPTS``
    consecutive failures (defined in crud.py) the account is
    locked and must be unlocked by an appropriately privileged
    user via the API.
    """

    __tablename__ = "staff_users"

    # Auto-incremented primary key.
    id = Column(Integer, primary_key=True, index=True)

    # Unique username — indexed for fast login lookups.
    username = Column(
        String(50), nullable=False, unique=True, index=True
    )

    # Stored as a pbkdf2_sha256 hash — never as plain text.
    password = Column(String(255), nullable=False)

    # One of 'staff', 'manager', or 'superadmin'.
    role = Column(String(20), nullable=False, default="staff")

    # Incremented on each failed login; reset to 0 on success.
    failed_login_attempts = Column(
        Integer, nullable=False, default=0
    )

    # Set True once failed_login_attempts reaches the lockout
    # threshold.  Locked users cannot log in until unlocked.
    is_locked = Column(Boolean, nullable=False, default=False)

    # True for seeded demo accounts and all newly created staff
    # users.  The UI redirects flagged users to the
    # password-change form on their first successful login.
    must_change_password = Column(
        Boolean, nullable=False, default=False
    )

    # Records when the most recent failed login occurred;
    # useful for implementing time-based unlock policies later.
    last_failed_login_at = Column(DateTime, nullable=True)

    # UTC timestamp of the most recent successful login.
    # NULL until the user has logged in at least once.
    last_login_at = Column(DateTime, nullable=True)

    # UTC timestamp of account creation.
    created_at = Column(
        DateTime, nullable=False, default=_now
    )


class Customer(Base):
    """Represents a bank customer and their account.

    I store balances as integers (pence) to avoid floating-
    point rounding errors that would occur with floats.
    The ``is_active`` flag controls whether the account can
    send or receive money — inactive accounts are rejected
    by all transaction endpoints.
    """

    __tablename__ = "customers"

    id = Column(Integer, primary_key=True, index=True)

    # Full legal name; the CustomerCreate schema enforces at
    # least two words via its ``validate_name`` validator.
    full_name = Column(String(100), nullable=False)

    # Unique email address — indexed for duplicate-check queries.
    email = Column(
        String(120), nullable=False, unique=True, index=True
    )

    # Format: "SB" followed by 8 digits, e.g. SB12345678.
    # Generated by generate_unique_account_number() in crud.py.
    account_number = Column(
        String(20), nullable=False, unique=True, index=True
    )

    # Current balance in pence.  Always a non-negative integer.
    balance = Column(Integer, nullable=False, default=0)

    # Inactive accounts cannot participate in any transaction.
    is_active = Column(Boolean, nullable=False, default=True)

    # Free-text notes entered by staff (e.g. contact preferences,
    # special circumstances).  NULL means no notes recorded.
    notes = Column(String(500), nullable=True)

    # created_at is set once at creation and never changed.
    # updated_at is refreshed on every edit or transaction so
    # the "last updated" display in the UI stays accurate.
    created_at = Column(
        DateTime, nullable=False, default=_now
    )
    updated_at = Column(
        DateTime, nullable=False, default=_now
    )

    # Transactions where this customer is the sender.
    # Used when building the customer timeline and detail view.
    outgoing_transactions = relationship(
        "Transaction",
        foreign_keys="Transaction.from_customer_id",
        back_populates="from_customer"
    )

    # Transactions where this customer is the recipient.
    incoming_transactions = relationship(
        "Transaction",
        foreign_keys="Transaction.to_customer_id",
        back_populates="to_customer"
    )


class Transaction(Base):
    """Records a single financial operation on the system.

    ``transaction_type`` is one of:
        deposit   — money added to an account (to_customer set).
        withdraw  — money removed from an account (from_customer).
        transfer  — money moved between two accounts (both set).

    ``risk_flag`` is set automatically by the crud layer when
    the transaction amount meets or exceeds
    ``SUSPICIOUS_TRANSACTION_THRESHOLD`` (currently £1 000).
    """

    __tablename__ = "transactions"

    id = Column(Integer, primary_key=True, index=True)

    # 'deposit', 'withdraw', or 'transfer'.
    transaction_type = Column(String(20), nullable=False)

    # Amount in pence — must be a positive integer.
    amount = Column(Integer, nullable=False)

    # Optional free-text note entered by the staff member.
    description = Column(String(255), nullable=True)

    # True when amount >= SUSPICIOUS_TRANSACTION_THRESHOLD.
    risk_flag = Column(Boolean, nullable=False, default=False)

    # NULL for deposits — no account sent the money.
    from_customer_id = Column(
        Integer, ForeignKey("customers.id"), nullable=True
    )

    # NULL for withdrawals — no account received the money.
    to_customer_id = Column(
        Integer, ForeignKey("customers.id"), nullable=True
    )

    # UTC timestamp when the transaction was recorded.
    created_at = Column(
        DateTime, nullable=False, default=_now
    )

    # ORM back-references to the related Customer objects.
    from_customer = relationship(
        "Customer",
        foreign_keys=[from_customer_id],
        back_populates="outgoing_transactions"
    )
    to_customer = relationship(
        "Customer",
        foreign_keys=[to_customer_id],
        back_populates="incoming_transactions"
    )


class AuditLog(Base):
    """Immutable record of every significant system event.

    I write an audit entry for every mutating operation:
    logins (success and failure), customer changes,
    transactions, staff management, and CSV exports.

    Entries are never modified after creation.  Old records
    can be bulk-purged via the manager-only endpoint
    ``DELETE /api/audit-logs?days=N``.

    ``result`` is typically ``"success"`` or ``"failure"``.
    ``actor`` is the username of the acting staff member, or
    ``"system"`` for automated seed operations, or
    ``"api_key_client"`` for API-key-authenticated calls.
    """

    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)

    # Short machine-readable event name.
    # Examples: 'login_failed', 'customer_create',
    # 'export_customers', 'staff_unlock'.
    event_type = Column(String(50), nullable=False)

    # Username of the staff member who triggered the event.
    actor = Column(String(50), nullable=False)

    # Human-readable description of what happened.
    details = Column(String(255), nullable=False)

    # 'success' or 'failure' — used for UI filtering.
    result = Column(
        String(20), nullable=False, default="success"
    )

    # IP address of the incoming request; NULL for internal
    # system operations that have no associated HTTP request.
    ip_address = Column(String(64), nullable=True)

    # UTC timestamp when the event was recorded.
    created_at = Column(
        DateTime, nullable=False, default=_now
    )
